package com.saivandan.crm.api;

import com.saivandan.crm.domain.AppUser; import com.saivandan.crm.repo.AppUserRepository; import com.saivandan.crm.security.JwtService; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/auth") public class AuthController {
  private final AppUserRepository users; private final PasswordEncoder encoder; private final JwtService jwt;
  public AuthController(AppUserRepository users,PasswordEncoder encoder,JwtService jwt){this.users=users;this.encoder=encoder;this.jwt=jwt;}
  @PostMapping("/login") public ResponseEntity<?> login(@Valid @RequestBody LoginRequest request){return users.findByUsername(request.username()).filter(AppUser::isActive).filter(u->encoder.matches(request.password(),u.getPasswordHash())).<ResponseEntity<?>>map(u->ResponseEntity.ok(new LoginResponse(jwt.create(u.getUsername(),u.getRole()),u.getUsername(),u.getDisplayName(),u.getRole()))).orElseGet(()->ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(new ErrorResponse("Invalid username or password")));}
  @GetMapping("/me") public UserResponse me(@org.springframework.security.core.annotation.AuthenticationPrincipal String username){AppUser u=users.findByUsername(username).orElseThrow();return new UserResponse(u.getUsername(),u.getDisplayName(),u.getRole());}
  @GetMapping("/users") public ResponseEntity<?> listUsers(){return ResponseEntity.ok(users.findAll().stream().map(u->new AdminUserResponse(u.getId(),u.getUsername(),u.getDisplayName(),u.getRole(),u.isActive())).toList());}
  @PostMapping("/users") public ResponseEntity<?> createUser(@Valid @RequestBody CreateUserRequest request){if(users.findByUsername(request.username()).isPresent())return ResponseEntity.status(HttpStatus.CONFLICT).body(new ErrorResponse("Username already exists"));AppUser user=users.save(new AppUser(request.username(),encoder.encode(request.password()),request.displayName(),request.role()));return ResponseEntity.status(HttpStatus.CREATED).body(new AdminUserResponse(user.getId(),user.getUsername(),user.getDisplayName(),user.getRole(),user.isActive()));}
  @DeleteMapping("/users/{id}") public ResponseEntity<?> deleteUser(@PathVariable Long id,@org.springframework.security.core.annotation.AuthenticationPrincipal String username){AppUser target=users.findById(id).orElseThrow();if(target.getUsername().equals(username))return ResponseEntity.badRequest().body(new ErrorResponse("You cannot delete your own account"));users.delete(target);return ResponseEntity.noContent().build();}
  public record LoginRequest(@NotBlank String username,@NotBlank String password){} public record LoginResponse(String token,String username,String displayName,String role){} public record UserResponse(String username,String displayName,String role){} public record AdminUserResponse(Long id,String username,String displayName,String role,boolean active){} public record CreateUserRequest(@NotBlank String username,@NotBlank String password,@NotBlank String displayName,@NotBlank String role){} public record ErrorResponse(String message){}
}
